name: daily-cron
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://vanderval-junior-blogr-nextjs-prisma.vercel.app/api/cron' \
          --header 'Authorization: Bearer ${{ process.env.API_SECRET_KEY }}'
